spring:
  application:
    name: store-app

  datasource:
    # CREATE DATABASE tsp;
    # CREATE USER tsp WITH PASSWORD 'tsp';
    # grant all privileges on database 'tsp' to tsp;
    url: jdbc:postgresql://localhost/tsp
    username: tsp
    password: tsp

  session:
    jdbc:
      initialize-schema: always
      table-name: store_app_session
      schema: classpath:/db/session-schema.sql
    timeout: PT768H

  security:
    user:
      name: tsp
      password: tsp

server:
  port: 8081
